# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_question_text', models.CharField(max_length=2000)),
                ('choice_answer_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CreateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(max_length=300)),
                ('createform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.CreateForm')),
            ],
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('choicequestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.ChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('question_answer', models.CharField(blank=True, max_length=2000)),
                ('customform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.CustomForm')),
            ],
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='customform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.CustomForm'),
        ),
    ]
