# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='choice_answer_text',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
