# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20160621_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='field_type',
            field=models.IntegerField(default=0),
        ),
    ]
