# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_customform_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='field_type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
