# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_remove_customform_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type_id', models.IntegerField()),
                ('field_type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=1000)),
                ('ftype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Ftype')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='ftype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='form.Ftype'),
        ),
    ]
