# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20160623_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type_id', models.IntegerField()),
                ('field_type', models.CharField(max_length=300)),
            ],
        ),
    ]
