# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_customform_type_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ftype',
        ),
        migrations.AddField(
            model_name='ftype',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='form.Question'),
        ),
    ]
