# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_auto_20160623_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftype',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type_id',
            field=models.IntegerField(default=0),
        ),
    ]
