# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_auto_20160623_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='ftype',
            new_name='question',
        ),
    ]
