# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_auto_20160623_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type_id',
        ),
        migrations.AddField(
            model_name='question',
            name='stype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='form.StandardField'),
        ),
    ]
