# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_auto_20160624_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='stype',
            new_name='ftype',
        ),
    ]
