# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_auto_20160624_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='unix_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='userid',
            field=models.ForeignKey(default=datetime.datetime(2016, 6, 25, 18, 57, 36, 780569), on_delete=django.db.models.deletion.CASCADE, to='form.Accounts'),
        ),
    ]
