# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_auto_20160625_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='userid',
            field=models.ForeignKey(default=datetime.datetime(2016, 6, 25, 19, 2, 26, 807158), on_delete=django.db.models.deletion.CASCADE, to='form.Accounts'),
        ),
    ]
