# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_auto_20160625_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Accounts'),
        ),
    ]
