# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0039_auto_20160626_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 26, 1, 11, 3, 13962)),
        ),
    ]
