# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0040_auto_20160626_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 26, 13, 56, 17, 403250)),
        ),
    ]
