# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_auto_20160626_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[['python', 'python']], default='python', max_length=100)),
                ('style', models.CharField(choices=[['python', 'python'], ['friendly', 'friendly']], default='friendly', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 26, 14, 46, 47, 887832)),
        ),
    ]
