# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0045_auto_20160627_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='owner',
            new_name='ownerr',
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 27, 12, 6, 0, 61256)),
        ),
    ]
