# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0046_auto_20160627_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='ownerr',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 27, 14, 46, 37, 714708)),
        ),
    ]
