# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0049_auto_20160628_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 0, 44, 5, 423818)),
        ),
    ]
