# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0051_auto_20160629_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='customform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.CustomForm'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 11, 54, 9, 463204)),
        ),
    ]
