# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 11:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0053_auto_20160629_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='accounts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 16, 38, 18, 387019)),
        ),
    ]
